# Generated by Django 3.2.8 on 2022-01-13 19:53

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('productName', models.CharField(max_length=1000)),
                ('productCostPrice', models.IntegerField()),
                ('productSellingPrice', models.IntegerField()),
                ('totalProduct', models.IntegerField()),
                ('availableProduct', models.IntegerField()),
                ('productDescription', models.CharField(max_length=1000, null=True)),
                ('totalProfit', models.IntegerField()),
            ],
        ),
    ]
