# Generated by Django 4.0.1 on 2022-01-14 13:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_alter_product_totalprofit'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='productCostPrice',
            new_name='bulkPrice',
        ),
        migrations.RenameField(
            model_name='product',
            old_name='productSellingPrice',
            new_name='unitSellingPrice',
        ),
    ]
