# Generated by Django 4.0.1 on 2022-01-14 16:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_rename_productcostprice_product_bulkprice_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='current_profit',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
    ]
